# Generated by Django 5.2.6 on 2025-09-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('size', models.CharField(blank=True, max_length=5)),
                ('sleeve_type', models.CharField(blank=True, max_length=20)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
