# Generated by Django 5.2.6 on 2025-09-17 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('size', models.CharField(blank=True, choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=4, null=True)),
                ('sleeve_type', models.CharField(blank=True, choices=[('none', 'None'), ('short', 'Short Sleeve'), ('long', 'Long Sleeve')], max_length=12, null=True)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
