# Generated by Django 5.2.6 on 2025-09-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kit',
            new_name='Product',
        ),
    ]
