# Generated by Django 5.2.6 on 2025-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey')], default='jersey', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sleeve_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('short', 'Short Sleeve'), ('long', 'Long Sleeve')], max_length=12, null=True),
        ),
    ]
