# Generated by Django 5.2.6 on 2025-09-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tes',
            field=models.IntegerField(default=0),
        ),
    ]
